version: '2'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    ports:
      - "80:80"
    links:
      - app
      
  app:
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: ./ancile-slackbot
      dockerfile: dev.Dockerfile
    expose:
      - "8000"
    links:
      - database
  
  database:
    image: postgres:9.6
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
       PGDATA: /var/lib/postgresql/data
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    

