version: '2'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
#      - outlook
      - class
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
      - "./certs:/etc/letsencrypt"
#
#  outlook:
#    environment:
#      DJANGO_MANAGEPY_MIGRATE: "on"
#    build:
#      context: ./slack_outlook
#      dockerfile: Dockerfile
#    links:
#      - database_outlook
#    volumes:
#      - "./migrations_outlook:/usr/src/app/ancile/slackbot/migrations"


  class:
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: ./slack_class
      dockerfile: Dockerfile
    links:
      - database_class
    volumes:
      - "./migrations_class:/usr/src/app/ancile/slackbot/migrations"

  
#  database_outlook:
#    image: postgres
#    expose:
#      - "5432"
#    environment:
#      PGDATA: /var/lib/postgresql/data
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./postgresql_outlook/data:/var/lib/postgresql/data

  database_class:
    image: postgres
    expose:
      - "5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql_class/data:/var/lib/postgresql/data